include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - 'test/firebase_numbers_repository_test.dart' # error • 'Mock.==' ('bool Function(Object)') isn't a valid concrete implementation of 'FirebaseFirestore.==' 
