name: numbers_repository
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  cloud_firestore: any
  equatable: any
  firebase_core: any
  flutter:
    sdk: flutter
  meta: any
  path: any
  rxdart: any

dev_dependencies:
  fake_cloud_firestore: any
  firebase_core_platform_interface: any
  flutter_test:
    sdk: flutter
  mocktail: any
  very_good_analysis: any
