name: numbers_repository

version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  rxdart: ^0.26.0
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
