// Mocks generated by Mockito 5.0.1 from annotations
// in numbers_repository/test/entities/number_entity_test.dart.
// Do not manually edit this file.

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeDocumentReference extends _i1.Fake implements _i2.DocumentReference {
}

class _FakeSnapshotMetadata extends _i1.Fake implements _i2.SnapshotMetadata {}

/// A class which mocks [DocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentSnapshot extends _i1.Mock implements _i2.DocumentSnapshot {
  MockDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  _i2.DocumentReference get reference =>
      (super.noSuchMethod(Invocation.getter(#reference),
          returnValue: _FakeDocumentReference()) as _i2.DocumentReference);
  @override
  _i2.SnapshotMetadata get metadata =>
      (super.noSuchMethod(Invocation.getter(#metadata),
          returnValue: _FakeSnapshotMetadata()) as _i2.SnapshotMetadata);
  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);
}
