name: major_system

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  schedule:
    - cron: '0 9 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Print Flutter/Dart version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --line-length 120 --set-exit-if-changed .

      - name: Analyze project source (type checking, etc)
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Ensure 90% test coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: ./coverage/lcov.info
          min_coverage: 90

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true