name: numbers_repository

on:
  push:
    branches: main
  pull_request:
    branches: main

  schedule:
    - cron: '0 9 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: packages/numbers_repository

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Print Flutter/Dart version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --dry-run --line-length 120 --set-exit-if-changed .

      - name: Analyze project source (type checking, etc)
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage --no-pub --test-randomize-ordering-seed random

      - name: 'Ensure 90% test coverage'
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: "./coverage/lcov.info"
          min_coverage: 90
          exclude: "**/*_observer.dart **/change.dart"

      - name: Install lcov (for `genhtml`)
        run: sudo apt-get install lcov

      - name: Generate HTML coverage page
        run: genhtml -o cov-output coverage/lcov.info

      - name: Zip up cov-output
        run: zip -r html-coverage.zip cov-output/

      - name: Upload test coverage info
        uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: coverage/lcov.info

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v2
        with:
          name: html-coverage
          path: html-coverage.zip
