name: packages

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  schedule:
    - cron: '0 9 * * 5'

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        directory:
          [
            '.',
            'packages/numbers_repository',
            'packages/authentication_repository',
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure fvm
        uses: kuhnroyal/flutter-fvm-config-action@v2
        with:
          setup: true
          cache: true

      - name: Print Flutter/Dart version
        working-directory: ${{ matrix.directory }}
        run: flutter --version

      - name: Install dependencies
        working-directory: ${{ matrix.directory }}
        run: flutter pub get

      - name: Verify formatting
        working-directory: ${{ matrix.directory }}
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: ${{ matrix.directory }}
        run: flutter analyze --fatal-infos .

      - name: Run tests
        working-directory: ${{ matrix.directory }}
        run: flutter test --test-randomize-ordering-seed=random --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
